title: List 45 - NFT trading
email: hello@desk520.com
description: "BFTs is one of the words you would hear from crypto OGs all the time. But that does not make it less important."
baseurl: ""
url: "https://list-45.vercel.app"
twitter_username: tradingfanbois
instagram_username:  bfx.referral.code
medium_username: cryptolounge

# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
